### ISSUE TITLE
Sending Email

### ISSUE THREAD

**Issue by grichardomi** [Mazbaul/Online-Learning-And-Course-Management-System#3]
Nice app.

I noticed it does not send email to new registered user.

What will it take to add this and other email functionalities?

Thanks

**Comment by Mazbaul** [comment]
email functionalities not added in it.i was thinking about to add it.
i will add it in future.if you want to add it you can use phpmailer or you can follow laravel mail documentation.
https://laravel.com/docs/5.2/mail

Thanks
